project:
  type: website
  output-dir: docs

website:
  title: "My First Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Viz"
        menu:
          - href: food.html
            text: "Food Consumption"
          - href: drinks.html
            text: "All Drinks"
          - href: miniproject2.html
            text: "Mini-Project 2: Netflix Analysis"
          - href: miniproject3.html
            text: "Mini-Project 3: March Madness"
          - href: miniproject4.html
            text: "Mini-Project 4: SQL Analysis"
      - href: finalproject.qmd
        
            
            

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual


