project:
  type: website
  output-dir: docs

website:
  title: "Chloe Denhart"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Viz"
        menu:
          - href: food.html
            text: "Food Consumption Analysis"
          - href: drinks.html
            text: "Drinks Analysis"
      - href: miniproject2.qmd
      - href: miniproject3.qmd
      - href: miniproject4.qmd
      - href: finalproject.qmd
      - href: Resume.qmd
        
            
            

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual


