project:
  type: website
  output-dir: docs

website:
  title: "My First Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Data Viz"
        menu:
          - href: food.html
            text: "Food Consumption"
          - href: drinks.html
            text: "All Drinks"
          - href: miniproject2.html
            text: "Mini-Project 2"
          - href: miniproject3.html
            text: "Mini-Project 3"
          - href: miniproject4.html
            text: "Mini-Project 4"
          - href: finalproject.html
            text: "Final Project"
        
            
            

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


