project:
  type: website
  output-dir: docs

website:
  title: "My First Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Data Viz"
        menu:
          - href: food.html
            text: "Food Consumption"
          - href: drinks.html
            text: "All Drinks"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


