project:
  type: website
  output-dir: docs

website:
  title: "My First Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Viz"
        menu:
          - href: food.html
            text: "Food Consumption Analysis"
          - href: drinks.html
            text: "Drinks Analysis"
          - href: miniproject2.qmd
          - href: miniproject3.qmd
          - href: miniproject4.qmd
      - href: finalproject.qmd
        
            
            

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual


