---
title: "Food Consumption"
description: |
  Analysis of food consumption data from TidyTuesday
author: Chloe Denhart
date: September 18, 2024
format: html
execute: 
  warning: false
  message: false
---

In this project, I analyze data from the TidyTuesday initiative, focusing on food consumption and its associated carbon dioxide (CO2) emissions. The dataset provides insights into the relationship between different types of food consumption and their environmental impact. By visualizing this relationship, I aim to identify patterns and highlight how dietary choices contribute to CO2 emissions, a critical factor in discussions on climate change and sustainability.

```{r}
food <- read.csv("food_consumption.csv")

library(tidyverse)
library(ggplot2)

# generating plot, co2 emmisions on x-axis, consumption on y-axis
ggplot(food, aes(x = co2_emmission, y = consumption)) +
  geom_point() +
  labs(
    x = "CO2 Emissions",
    y = "Consumption",
    title = "Relationship food consumption and CO2 emissions",
  )
```

Using the dataset `food_consumption.csv`, I created a scatter plot that depicts the relationship between food consumption levels (measured in kilograms per capita) and CO2 emissions (measured in kilograms of CO2 equivalent). This plot serves to illustrate whether foods with higher consumption rates also tend to have higher associated CO2 emissions.

**Data Source**:\
<https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-05-26/all_drinks.csv>\

**Author**: TidyTuesday Project

This data was sourced from the TidyTuesday project, which focuses on weekly data challenges for the R community. Specifically, the data pertains to food consumption by different drinks:

-   The dataset was updated on May 26, 2020.

-   It includes data related to the consumption of various drinks, with a focus on their distribution and popularity across different regions.

-   The data spans various food and drink categories and provides detailed consumption statistics.
